#
# -*- coding: utf-8 -*-
# Copyright 2023 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the awplus_rip module
"""


class RipArgs(object):  # pylint: disable=R0903
    """The arg spec for the awplus_rip module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
            'options': {'administrative_distance': {'options': {'address': {'type': 'str'},
                                                                'distance': {'required': True,
                                                                             'type': 'int'}},
                                                    'type': 'dict'},
                        'neighbors': {'elements': 'str', 'type': 'list'},
                        'networks': {'elements': 'str', 'type': 'list'},
                        'passive_interfaces': {'elements': 'str',
                                               'type': 'list'},
                        'timers': {'options': {'garbage_collection': {'default': 120,
                                                                      'type': 'int'},
                                               'routing_table_timeout': {'default': 180,
                                                                         'type': 'int'},
                                               'routing_table_update': {'default': 30,
                                                                        'type': 'int'}},
                                   'type': 'dict'},
                        'version': {'choices': ['1', '2'],
                                    'default': 2,
                                    'type': 'int'}},
            'type': 'list'},
 'state': {'choices': ['merged', 'replaced', 'overridden', 'deleted'],
           'default': 'merged', 'type': 'str'}}  # pylint: disable=C0301
