---
- hosts: all
  connection: network_cli
  collections:
    - alliedtelesis.awplus
  tasks:
    - name: testing out rip module
      alliedtelesis.awplus.awplus_rip:
        config:
          version: 1
        state: overridden
