#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2023 Allied Telesis
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for awplus_rip
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': 'network'
}

DOCUMENTATION = """
---
module: awplus_rip
version_added: 2.19
short_description: Manage the rip router attributes on AlliedWare Plus devices
description:
    - This module provides declarative management of rip router attributes
      on awplus devices. It provides an option to configure host system
      parameters or remove those parameters from the device active
      configuration.
author:
  - Ryan Scofield
notes:
  - Tested against ???
options:
  config:
    description: Configuration of the RIP module.
    type: list
    elements: dict
    suboptions:
      neighbors:
        description:
          - Used to specify a neighbor router.
        type: list
        elements: str
      networks:
        description:
          - Used to specify networks or VLANs, to which rip routing
            information will be sent and received.
        type: list
        elements: str
      passive_interfaces:
        description:
          - Command for blocking RIP broadcasts on the interface.
        type: list
        elements: str
      administrative_distance:
        description:
          - Set the RIP administrative distance globally, for an address, 
            or for a range of addresses.
        type: dict
        suboptions:
          distance:
            description:
              - The administrative distance for RIP.
            required: True
            type: int
          address:
            description:
              - The address or range of addresses to configure the 
                RiP administrative distance for.
            type: str
      timers:
        description:
          - Configure RIP timers.
        type: dict
        suboptions:
          routing_table_update:
            description:
              - The routing table update timer.
            default: 30
            type: int
          routing_table_timeout:
            description:
              - The routing information timeout timer.
            default: 180
            type: int
          garbage_collection:
            description:
              - The garbage collection timer.
            default: 120
            type: int
      version:
        description:
          - Set the version of RIP used.
        default: 2
        choices: ['1', '2']
        type: int
  state:
    description:
      - The state the configuration should be left in, defaults to merged
    choices:
      - merged
      - replaced
      - overridden
      - deleted
    default: merged
"""
EXAMPLES = """
# Using merged

# Before state:
# -------------
# awplus(config-router)#show running-config router rip
# !
# router rip
#  network vlan2
#  neighbor 1.1.1.1
#  passive-interface vlan3
#  timers basic 25 80 100
#  distance 100 1.2.3.4/32 
# !

- name: Merge config
  alliedtelesis.awplus.awplus_rip:
    config:
      networks: 
        - vlan3
      timers:
        routing_table_update: 50
    state: replaced

# awplus(config-router)#show running-config router rip
# !
# router rip
#  network vlan2
#  network vlan3
#  neighbor 1.1.1.1
#  passive-interface vlan3
#  timers basic 50 80 100
#  distance 100 1.2.3.4/32 
# !


# Using replaced

# Before state:
# -------------
# awplus(config-router)#show running-config router rip
# !
# router rip
#  network vlan2
#  neighbor 1.1.1.1
#  passive-interface vlan3
#  timers basic 25 80 100
#  distance 100 1.2.3.4/32 
# !

- name: Replace config
  alliedtelesis.awplus.awplus_rip:
    config:
      network: 
        - vlan3
      timers:
        routing_table_update: 50
    state: replaced

# awplus(config-router)#show running-config router rip
# !
# router rip
#  network vlan2
#  network vlan3
#  neighbor 1.1.1.1
#  passive-interface vlan3
#  timers basic 50 180 120
#  distance 100 1.2.3.4/32 
# !


# Using overridden

# Before state:
# -------------
# awplus(config-router)#show running-config router rip
# !
# router rip
#  network vlan2
#  neighbor 1.1.1.1
#  passive-interface vlan3
#  timers basic 25 80 100
#  distance 100 1.2.3.4/32 
# !

- name: Override config
  alliedtelesis.awplus.awplus_rip:
    config:
      network: 
        - vlan2
      neighbor: 
        - 1.2.3.4
    state: overridden

# awplus(config-router)#show running-config router rip
# !
# router rip
#  network vlan2
#  neighbor 1.2.3.4
# !


# Using deleted

# Before state:
# -------------
# awplus(config-router)#show running-config router rip
# !
# router rip
#  network vlan2
#  network vlan3
#  neighbor 1.1.1.1
#  passive-interface vlan3
#  timers basic 25 80 100
#  distance 100 1.2.3.4/32 
# !

- name: Delete config
  alliedtelesis.awplus.awplus_rip:
    config:
      neighbors: 
        - 1.1.1.1
      networks: 
        - vlan2
      passive_interfaces: 
        - vlan3
      administrative_distance:
        distance: 100
        address: 1.2.3.4/32
      timers:
        routing_table_update: 25
        routing_table_timeout: 80
        garbage_collection: 100
    state: deleted

# awplus(config-router)#show running-config router rip
# !
# router rip
#  network vlan3
# !


"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['router rip', 'no network 1.3.3.4', 'network 195.46.3.4']

"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.argspec.rip.rip import RipArgs
from ansible_collections.alliedtelesis.awplus.plugins.module_utils.network.awplus.config.rip.rip import Rip


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=RipArgs.argument_spec,
                           supports_check_mode=True)

    result = Rip(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
